[tool.black]
line-length = 100
target-version = ["py311", "py313"]

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "UP", "B"]
ignore = []
target-version = "py311"
exclude = ["venv", "storage", "artifacts"]

[tool.mypy]
python_version = "3.11"
strict = false
ignore_missing_imports = true
exclude = "venv|artifacts|storage"
